# Generated by Django 2.2 on 2021-01-16 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Monster',
                'verbose_name_plural': 'Monsters',
            },
        ),
        migrations.CreateModel(
            name='MonsterHunterDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_channel', models.CharField(max_length=60, verbose_name='Discord Channel')),
            ],
            options={
                'verbose_name': 'Monster Hunter Database',
                'verbose_name_plural': 'Monster Hunter Databases',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
            },
        ),
        migrations.CreateModel(
            name='PlatformReleasedSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Platform', verbose_name='Platform')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Weapon',
                'verbose_name_plural': 'Weapons',
            },
        ),
        migrations.CreateModel(
            name='SeriesWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.MonsterHunterDatabase', verbose_name='Series Name')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Weapon', verbose_name='Weapon')),
            ],
            options={
                'verbose_name': 'Available Weapon',
                'verbose_name_plural': 'Available Weapons',
            },
        ),
        migrations.CreateModel(
            name='SeriesTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('platform', models.ManyToManyField(through='dashboard.PlatformReleasedSeries', to='dashboard.Platform', verbose_name='Platforms')),
            ],
            options={
                'verbose_name': 'Series Title',
                'verbose_name_plural': 'Series Titles',
            },
        ),
        migrations.CreateModel(
            name='SeriesMonster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.MonsterHunterDatabase', verbose_name='Series Name')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Monster', verbose_name='Monster')),
            ],
            options={
                'verbose_name': 'Available Monster',
                'verbose_name_plural': 'Available Monsters',
            },
        ),
        migrations.AddField(
            model_name='platformreleasedseries',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.SeriesTitle', verbose_name='Series Title'),
        ),
        migrations.AddField(
            model_name='monsterhunterdatabase',
            name='series',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.SeriesTitle', verbose_name='Series Name'),
        ),
    ]
