# Generated by Django 2.2 on 2021-01-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriestitle',
            name='aliases',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Game Name Aliases'),
        ),
        migrations.AddField(
            model_name='seriestitle',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
