# Generated by Django 2.2 on 2021-01-17 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210117_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('prop_grouping', models.CharField(choices=[('other', 'Other'), ('style', 'Style')], max_length=20, verbose_name='Label')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.MonsterHunterDatabase', verbose_name='Series Name')),
            ],
            options={
                'verbose_name': 'Additional Properties',
                'verbose_name_plural': 'Additional Properties',
            },
        ),
    ]
