# Generated by Django 2.2 on 2021-01-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_additionalproperties'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalproperties',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
